# Generated by Django 2.0.3 on 2018-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umls',
            name='Diseasename',
            field=models.CharField(max_length=200),
        ),
    ]
