# Generated by Django 2.0.3 on 2018-05-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_auto_20180503_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umls',
            name='Code',
            field=models.CharField(max_length=70),
        ),
    ]
