# Generated by Django 2.0.3 on 2018-05-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='testcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresults',
            name='testvalue',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
