# Generated by Django 2.0.3 on 2018-05-21 10:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0002_auto_20180520_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=3),
            preserve_default=False,
        ),
    ]
