# Generated by Django 2.0.3 on 2018-05-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0005_merge_20180523_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='discode',
            field=models.CharField(max_length=10),
        ),
    ]
