# Generated by Django 2.0.3 on 2018-05-23 08:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0006_auto_20180523_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Female'), ('M', 'Male')], max_length=3, null=True),
        ),
    ]
