# Generated by Django 2.0.3 on 2018-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0009_auto_20180523_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedmodel',
            name='mrno',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
