# Generated by Django 2.0.3 on 2018-05-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0010_predictedmodel_mrno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedmodel',
            name='mrno',
        ),
        migrations.AlterField(
            model_name='predictedmodel',
            name='patient',
            field=models.ForeignKey(db_column='mrno', on_delete=django.db.models.deletion.CASCADE, to='patientdetails.Patient'),
        ),
    ]
