# Generated by Django 2.0.3 on 2018-05-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0013_auto_20180523_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='patient',
            field=models.ForeignKey(db_column='mrno', on_delete=django.db.models.deletion.CASCADE, to='patientdetails.Patient', to_field='mrno'),
        ),
    ]
