# Generated by Django 2.0.3 on 2018-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0017_auto_20180523_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='Range',
            field=models.CharField(max_length=30),
        ),
    ]
