# Generated by Django 2.0.3 on 2018-05-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0018_auto_20180523_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresults',
            name='regno',
        ),
    ]
