# Generated by Django 2.0.3 on 2018-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0019_remove_testresults_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='infer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('symptom1', models.CharField(max_length=10)),
                ('symptom2', models.CharField(max_length=10)),
                ('symptom3', models.CharField(max_length=10)),
            ],
        ),
    ]
