# Generated by Django 2.0.3 on 2018-05-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0021_auto_20180523_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='infer',
        ),
    ]
