# Generated by Django 2.0.3 on 2018-05-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0023_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcode', models.CharField(max_length=3)),
                ('testname', models.CharField(max_length=20)),
                ('f_max', models.DecimalField(decimal_places=5, max_digits=10)),
                ('m_max', models.DecimalField(decimal_places=5, max_digits=10)),
                ('m_min', models.DecimalField(decimal_places=5, max_digits=10)),
                ('f_min', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
