# Generated by Django 2.0.3 on 2018-05-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0024_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='f_max',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tests',
            name='f_min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tests',
            name='m_max',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tests',
            name='m_min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
