# Generated by Django 2.0.3 on 2018-05-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0025_auto_20180524_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='testcode',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
