# Generated by Django 2.0.3 on 2018-05-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0027_auto_20180524_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesparam',
            name='rules',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patientdetails.rules'),
            preserve_default=False,
        ),
    ]
