# Generated by Django 2.0.3 on 2018-05-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0029_auto_20180524_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesparam',
            name='rules',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patientdetails.rules'),
        ),
    ]
