# Generated by Django 2.0.3 on 2018-05-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0030_auto_20180524_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='rulesparams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=10)),
                ('Diagnosis', models.ForeignKey(db_column='discode', on_delete=django.db.models.deletion.CASCADE, to='patientdetails.Diagnosis', to_field='discode')),
                ('rules', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patientdetails.rules')),
                ('testcode', models.ForeignKey(db_column='testcode', on_delete=django.db.models.deletion.CASCADE, to='patientdetails.tests', to_field='testcode')),
            ],
        ),
        migrations.RemoveField(
            model_name='rulesparam',
            name='Diagnosis',
        ),
        migrations.RemoveField(
            model_name='rulesparam',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='rulesparam',
            name='testcode',
        ),
        migrations.DeleteModel(
            name='rulesparam',
        ),
    ]
