# Generated by Django 2.0.3 on 2018-05-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0031_auto_20180524_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='rulesparams',
            name='rules',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patientdetails.rule'),
        ),
        migrations.DeleteModel(
            name='rules',
        ),
    ]
