# Generated by Django 2.0.3 on 2018-05-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientdetails', '0032_auto_20180524_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdetails.Patient'),
        ),
    ]
