# Generated by Django 2.0.2 on 2018-05-24 01:40

from django.db import models, migrations
from django.contrib.auth.models import Group, Permission



def add_group_permissions(apps, schema_editor):
    #non staff
    group, created = Group.objects.get_or_create(name='non_staff')
    if created:

        group.save()

    #assistant
    group, created = Group.objects.get_or_create(name='assistant')
    if created:
        #group.permissions.add(can_edit_users)

        group.save()

    #doctor
    group, created = Group.objects.get_or_create(name='doctor')
    if created:
        # group.permissions.add('pateintdetails.view_patient', 'pateintdetails.add_patient', 'pateintdetails.change_patient', 'pateintdetails.delete_patient')
  
        group.save()


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
